module.exports = grammar({
  name: "pebble",

  extras: ($) => [/[ \t\r\n]/, $.comment],
  word: ($) => $.identifier,
  conflicts: ($) => [
    [$.named_type],
    [$.named_type, $._expression],
    [$.slice_type, $.array_expression],
    [$.array_type, $.array_expression],
    [$.syntax_term, $.array_expression],
    [$.parameter_list, $.function_type],
    [$.parameter, $.named_type],
    [$.member_suffix, $.partial_member_expression],
    [$.record_expression, $.record_suffix],
  ],

  rules: {
    source_file: ($) => repeat($._declaration),
    comment: ($) => token(seq("//", /.*/)),

    _declaration: ($) => choice($.import_declaration, $.binding_declaration,
      $.type_declaration, $.function_declaration, $.extern_declaration),
    import_declaration: ($) => seq("import", $.string_literal, ";"),
    binding_declaration: ($) => seq(choice("let", "var"), $.identifier,
      optional($._type), optional(seq("=", $._expression)), ";"),
    type_declaration: ($) => seq("type", $.identifier, optional($.type_parameters),
      "=", $._type, ";"),
    type_parameters: ($) => seq("[", commaSep1($.type_parameter), "]"),
    type_parameter: ($) => $.identifier,

    function_declaration: ($) => seq("fn", optional("inline"),
      optional($.string_literal), $.identifier, optional($.type_parameters),
      $.parameter_list, $._type, choice($.block, seq("=>", $._expression, ";"))),
    parameter_list: ($) => seq("(", optional(commaSep1($.parameter)), ")"),
    parameter: ($) => seq(optional("..."), commaSep1($.identifier), $._type),

    extern_declaration: ($) => seq("extern", optional($.string_literal),
      choice($.extern_block, $.extern_item)),
    extern_block: ($) => seq("{", repeat($.extern_item), "}"),
    extern_item: ($) => choice(
      seq("fn", $.identifier, $.parameter_list, $._type, ";"),
      seq("type", $.identifier, ";"),
      seq(choice("let", "var"), $.identifier, $._type, ";")),

    _type: ($) => choice($.named_type, $.pointer_type, $.optional_type,
      $.array_type, $.slice_type, $.function_type, $.grouped_type,
      $.struct_type, $.union_type, $.enum_type),
    named_type: ($) => seq($.identifier, repeat(seq("::", $.identifier)),
      optional($.type_arguments)),
    type_arguments: ($) => seq("[", commaSep1($._type), "]"),
    pointer_type: ($) => prec.right(seq("*", $._type)),
    optional_type: ($) => prec.right(seq("?", $._type)),
    array_type: ($) => seq("[", $._expression, "]", $._type),
    slice_type: ($) => seq("[", "]", $._type),
    function_type: ($) => seq("fn", optional($.string_literal), "(",
      optional(commaSep1($._type)), ")", $._type),
    grouped_type: ($) => seq("(", commaSep1($._type), ")"),
    struct_type: ($) => seq("struct", "{", repeat($.aggregate_member), "}"),
    union_type: ($) => seq("union", optional("enum"), "{", repeat($.union_member), "}"),
    enum_type: ($) => seq("enum", "{", optional(seq(commaSep1($.identifier), optional(","))), "}"),
    aggregate_member: ($) => choice($.function_declaration,
      seq(commaSep1($.identifier), $._type, ";")),
    union_member: ($) => choice($.function_declaration,
      seq(commaSep1($.identifier), $._type, ";")),

    block: ($) => seq("{", repeat($._statement), "}"),
    _statement: ($) => choice($.block, $.binding_declaration, $.return_statement,
      $.if_statement, $.while_statement, $.range_loop_statement, $.for_statement,
      $.switch_statement, $.defer_statement, $.print_statement, $.jump_statement,
      $.assignment_or_expression_statement),
    return_statement: ($) => seq("return", optional($._expression), ";"),
    if_statement: ($) => prec.right(seq("if", $._expression, $._statement,
      optional(seq("else", $._statement)))),
    while_statement: ($) => seq("while", $._expression, $._statement),
    range_loop_statement: ($) => seq("loop", $._expression,
      choice("..", "..="), $._expression, optional(seq(":", $.identifier)), $._statement),
    for_statement: ($) => seq("for", optional(choice(
      seq(choice("let", "var"), $.identifier, optional($._type), optional(seq("=", $._expression))),
      $.assignment_or_expression_statement_no_semicolon)), ";",
      optional($._expression), ";", optional($.assignment_or_expression_statement_no_semicolon),
      $._statement),
    assignment_or_expression_statement_no_semicolon: ($) => seq($._expression,
      optional(seq($.assignment_operator, $._expression))),
    switch_statement: ($) => seq("switch", $._expression, "{", repeat1($.switch_case), "}"),
    switch_case: ($) => seq(choice(seq("case", commaSep1($._expression)), "else"), ":", $._statement),
    defer_statement: ($) => seq("defer", $._statement),
    print_statement: ($) => seq(choice("print", "println"), commaSep1($._expression), ";"),
    jump_statement: ($) => seq(choice("break", "continue"), ";"),
    assignment_or_expression_statement: ($) => seq($._expression,
      optional(seq($.assignment_operator, $._expression)), ";"),
    assignment_operator: ($) => choice("=", "+=", "-=", "*=", "/=", "%="),

    _expression: ($) => choice($.binary_expression, $.cast_expression,
      $.prefix_expression, $.call_expression, $.field_expression,
      $.index_expression, $.path_expression, $.record_construction_expression,
      $.postfix_operator_expression, $.identifier, $.literal,
      $.context_expression, $.some_expression, $.sizeof_expression,
      $.slice_expression, $.grouped_expression, $.array_expression,
      $.function_literal, $.record_expression, $.partial_member_expression),
    binary_expression: ($) => choice(
      prec.left(1, seq($._expression, "||", $._expression)),
      prec.left(2, seq($._expression, "&&", $._expression)),
      prec.left(3, seq($._expression, "|", $._expression)),
      prec.left(4, seq($._expression, "^", $._expression)),
      prec.left(5, seq($._expression, "&", $._expression)),
      prec.left(6, seq($._expression, choice("==", "!="), $._expression)),
      prec.left(7, seq($._expression, choice("<", "<=", ">", ">="), $._expression)),
      prec.left(8, seq($._expression, choice("<<", ">>"), $._expression)),
      prec.left(9, seq($._expression, choice("+", "-"), $._expression)),
      prec.left(10, seq($._expression, choice("*", "/", "%"), $._expression))),
    cast_expression: ($) => prec.left(18, seq($._expression, "as", $._type)),
    prefix_expression: ($) => prec.right(19, seq(choice("-", "!", "&", "*", "~"),
      $._expression)),
    call_suffix: ($) => prec(30, seq("(", optional(commaSep1($._expression)), ")")),
    call_expression: ($) => prec(30, seq(field("function", $._expression), $.call_suffix)),
    bracket_suffix: ($) => seq("[", choice(seq(optional($._expression), ":", optional($._expression)),
      commaSep1($.syntax_term)), "]"),
    index_expression: ($) => prec(30, seq(field("operand", $._expression), $.bracket_suffix)),
    syntax_term: ($) => choice($._expression, $._type),
    member_suffix: ($) => seq(".", choice($.identifier, $.integer_literal)),
    field_expression: ($) => prec(30, seq(field("value", $._expression), $.member_suffix)),
    path_suffix: ($) => seq("::", $.identifier),
    path_expression: ($) => prec(30, seq($._expression, $.path_suffix)),
    record_construction_expression: ($) => prec(30,
      seq($._expression, $.record_suffix)),
    postfix_operator_expression: ($) => prec(30,
      seq($._expression, choice("!", "++", "--"))),
    context_expression: ($) => "context",
    some_expression: ($) => seq("some", $._expression),
    sizeof_expression: ($) => seq("sizeof", $._type),
    slice_expression: ($) => seq("slice", $._expression, ",", $._expression),
    grouped_expression: ($) => seq("(", commaSep1($._expression), ")"),
    array_expression: ($) => seq("[", optional(choice(seq($._expression, ";", $._expression),
      seq(commaSep1($._expression), optional(",")))), "]"),
    function_literal: ($) => seq("fn", optional("inline"), optional($.string_literal),
      optional($.type_parameters), $.parameter_list, $._type,
      choice($.block, seq("=>", $._expression))),
    record_expression: ($) => seq(".", "{", commaSep1($.record_field), optional(","), "}"),
    record_suffix: ($) => seq(".", "{", commaSep1($.record_field), optional(","), "}"),
    record_field: ($) => seq($.identifier, "=", $._expression),
    partial_member_expression: ($) => seq(".", $.identifier),

    literal: ($) => choice($.integer_literal, $.float_literal, $.string_literal,
      $.character_literal, $.boolean_literal, $.nil_literal, $.none_literal,
      $.interpolated_string),
    integer_literal: ($) => /(?:0[xX][0-9a-fA-F_]+|0[bB][01_]+|[0-9][0-9_]*)/,
    float_literal: ($) => /[0-9][0-9_]*\.[0-9][0-9_]*(?:[eE][+-]?[0-9][0-9_]*)?/,
    string_literal: ($) => seq('"', repeat(choice($.escape_sequence, /[^"\\\r\n]/)), '"'),
    character_literal: ($) => seq("'", choice($.escape_sequence, /[^'\\\r\n]/), "'"),
    escape_sequence: ($) => token(seq("\\", choice(/[nrt0\\"']/,
      /x[0-9a-fA-F]{2}/, /u\{[0-9a-fA-F]{1,6}\}/))),
    boolean_literal: ($) => choice("true", "false"),
    nil_literal: ($) => "nil",
    none_literal: ($) => "none",
    interpolated_string: ($) => seq("`", repeat(choice($.interpolation_text,
      seq("{", $._expression, "}"))), "`"),
    interpolation_text: ($) => token(prec(1, /[^`{}]+/)),
    identifier: ($) => /[a-zA-Z_][a-zA-Z0-9_]*/,
  },
});

function commaSep1(rule) {
  return seq(rule, repeat(seq(",", rule)));
}
