id = "pebble"
name = "Pebble"
version = "0.1.0"
schema_version = 1
grammar = "pebble"
authors = ["Joshua Pepple"]
repository = "https://github.com/pepplejoshua/pebble"

[grammars.pebble]
repository = "https://github.com/pepplejoshua/pebble"
rev = "c63f3a41b3b1dcf088e67fd627d64f7f32b55f80"
path = "editors/syght/grammar"
